In [1]:
from pathlib import Path
import sys

cwd = Path.cwd()
if (cwd / "src").exists():
    project_root = cwd
elif (cwd.parent / "src").exists():
    project_root = cwd.parent
else:
    raise FileNotFoundError("Could not locate project root containing 'src'.")

if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

In [2]:
from src.data.create_dataframes import sek_df2

sek_df2.head()

c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'FX', column 'USDNOK Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'FX', column 'USDKRW Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'FX', column 'USDSGD Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'FX', column 'USDTWD Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'FX', column 'USDMXN Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'FX', column 'USDCNH Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'FX', column 'USDINR Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'FX', column 'BBDXY Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'FX', column 'EMFXDBET Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'USGG2YR Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'USGG5YR Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'USGG10YR Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'S0042FS 3M1M BLC Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'S0042FS 6M1M BLC Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'S0042FS 1Y1M BLC Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'RR2YHUS Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'SPX Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'FTW5000 Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'INDU Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'MXUS Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'BCOM Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'CO1 Comdty'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'XAU Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'FN1 Comdty'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'TZT1 Comdty'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'NG1 COMB Comdty'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'HGA Comdty'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'LMCADS03 Comdty'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'VIX Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'MOVE Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'JPMVG71M Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'EUR', column 'GECU2YR Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'EUR', column 'GECU5YR Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'EUR', column 'GECU10YR Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'EUR', column 'RR2YHEA Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'EUR', column 'GTITL10YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'EUR', column 'GTDEM10YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'EUR', column 'SXXP Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'JPY', column 'GTJPY2YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'JPY', column 'GTJPY5YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'JPY', column 'GTJPY10YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'JPY', column 'G0018 3M1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'JPY', column 'G0018 6M1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'JPY', column 'G0018 1Y1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'JPY', column 'JYSST10 BLC Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'JPY', column 'NXY Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CHF', column 'GTCHF2YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CHF', column 'GTCHF5YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CHF', column 'GTCHF10YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CHF', column 'G0082 3M1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CHF', column 'G0082 6M1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CHF', column 'G0082 1Y1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CHF', column 'SMI Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'GBP', column 'GTGBP2YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'GBP', column 'GTGBP5YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'GBP', column 'GTGBP10YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'GBP', column 'RR2YHGB Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'GBP', column 'UKX Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'GBP', column 'MCX Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NZD', column 'GTNZD2YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NZD', column 'GTNZD5YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NZD', column 'G0049 3M1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NZD', column 'G0049 6M1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NZD', column 'G0049 1Y1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NZD', column 'RR2YHnz Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NZD', column 'NZX20X Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NZD', column 'OMRA Comdty'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NZD', column 'FSPA Comdty'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'AUD', column 'GTAUD2YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'AUD', column 'GTAUD5YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'AUD', column 'G0001 3M1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'AUD', column 'G0001 6M1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'AUD', column 'G0001 1Y1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'AUD', column 'RR2YHAU Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'AUD', column 'AS51 Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'AUD', column 'SCOH6 COMB Comdty'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'AUD', column 'IACA COMB Comdty'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CAD', column 'GTCAD2YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CAD', column 'G0007 3M1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CAD', column 'G0007 6M1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CAD', column 'G0007 1Y1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CAD', column 'RR2YHCA Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CAD', column 'SPTSX Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CAD', column 'USCRWCAS Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NOK', column 'GTNOK2YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NOK', column 'GTNOK5YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NOK', column 'GTNOK10YR Corp'; those rows will be NaT
  warnings.warn(

,GTSEK2YR Corp,GTSEK5YR Corp,GTSEK10YR Corp,RR2YHSE Index,OMX Index,USGG2YR Index,USGG5YR Index,USGG10YR Index,RR2YHUS Index,SPX Index,...,TZT1 Comdty,NG1 COMB Comdty,HGA Comdty,LMCADS03 Comdty,VIX Index,MOVE Index,JPMVG71M Index,USDSEK Curncy,BBDXY Curncy,EMFXDBET Index
2000-03-01,NaN,NaN,NaN,4.35,1463.75,6.504,6.571,6.386,2.74186,1379.19,...,NaN,2.815,NaN,1773.0,21.64,104.14,NaN,8.6590,NaN,99.75
2000-03-02,NaN,NaN,NaN,4.38,1515.62,6.513,6.583,6.384,2.75086,1381.76,...,NaN,2.783,NaN,1752.0,21.06,99.68,NaN,8.7761,NaN,99.63
2000-03-03,NaN,NaN,NaN,4.37,1530.02,6.495,6.593,6.388,2.73286,1409.17,...,NaN,2.825,NaN,1761.0,19.21,94.85,NaN,8.7985,NaN,99.55
2000-03-06,NaN,NaN,NaN,4.38,1537.33,6.529,6.625,6.411,2.76686,1391.28,...,NaN,2.850,NaN,1768.0,21.50,92.06,NaN,8.7910,NaN,99.50
2000-03-07,NaN,NaN,NaN,4.38,1539.00,6.486,6.569,6.373,2.72386,1355.62,...,NaN,2.799,NaN,1749.0,24.31,97.13,NaN,8.7779,NaN,99.53

In [3]:
from src.data.create_dataframes import df2_map, frames

sorted(df2_map.keys())

['aud',
 'aud_df2',
 'cad',
 'cad_df2',
 'chf',
 'chf_df2',
 'eur',
 'eur_df2',
 'gbp',
 'gbp_df2',
 'jpy',
 'jpy_df2',
 'nok',
 'nok_df2',
 'nzd',
 'nzd_df2',
 'sek',
 'sek_df2']

In [4]:
df2_map["nok_df2"].head()

,GTNOK2YR Corp,GTNOK5YR Corp,GTNOK10YR Corp,RR2YHNO Index,OBX Index,USGG2YR Index,USGG5YR Index,USGG10YR Index,RR2YHUS Index,SPX Index,...,TZT1 Comdty,NG1 COMB Comdty,HGA Comdty,LMCADS03 Comdty,VIX Index,MOVE Index,JPMVG71M Index,USDNOK Curncy,BBDXY Curncy,EMFXDBET Index
2000-03-01,NaN,NaN,NaN,3.64,150.775,6.504,6.571,6.386,2.74186,1379.19,...,NaN,2.815,NaN,1773.0,21.64,104.14,NaN,8.2904,NaN,99.75
2000-03-02,NaN,NaN,NaN,3.65,150.816,6.513,6.583,6.384,2.75086,1381.76,...,NaN,2.783,NaN,1752.0,21.06,99.68,NaN,8.3528,NaN,99.63
2000-03-03,NaN,NaN,NaN,3.65,151.840,6.495,6.593,6.388,2.73286,1409.17,...,NaN,2.825,NaN,1761.0,19.21,94.85,NaN,8.4157,NaN,99.55
2000-03-06,NaN,NaN,NaN,3.66,152.813,6.529,6.625,6.411,2.76686,1391.28,...,NaN,2.850,NaN,1768.0,21.50,92.06,NaN,8.4259,NaN,99.50
2000-03-07,NaN,NaN,NaN,3.63,157.516,6.486,6.569,6.373,2.72386,1355.62,...,NaN,2.799,NaN,1749.0,24.31,97.13,NaN,8.4171,NaN,99.53

In [11]:
from src.data.create_dataframes import processed_df_map, nzd_df_processed, aud_df_processed

nzd_df_processed.tail()

,NZDUSD,BBDXY,Asia EMFX,2y yield,5y yield,10y yield,Real 2y yield,Local - S&P500,Local - Wilshire,Local - Dow Jones,...,UK Natural Gas,TTF Natural Gas,NY Natural Gas,Copper COMEX,Copper LME,VIX,USTs Volatility,G10 FX Volatility,Whole milk,Skimmed milk
2026-02-13,0.000497,-0.000685,0.002090,0.0123,0.0077,-0.0012,0.0483,-0.025701,-0.026914,-0.026191,...,-0.012771,-0.015086,0.008050,0.002904,0.000427,-0.010623,0.022068,-0.015405,0.004003,0.000000
2026-02-16,-0.000994,0.001353,-0.001826,-0.0290,-0.0290,-0.0280,0.0000,-0.005580,-0.005580,-0.005580,...,-0.049741,-0.050387,0.000000,0.000000,-0.002371,0.028710,0.000000,-0.055866,-0.002667,-0.018538
2026-02-17,0.002649,0.000296,0.000529,-0.0449,-0.0332,-0.0275,-0.0249,-0.007377,-0.007266,-0.006998,...,-0.019767,-0.035607,-0.067606,-0.027408,-0.018139,-0.043873,-0.018138,-0.001369,0.001334,-0.000832
2026-02-18,-0.009635,0.002085,0.000333,-0.1292,-0.1184,-0.0761,-0.0312,0.008244,0.007398,0.009484,...,0.071604,0.051880,-0.018985,0.024932,0.000000,-0.066742,0.000000,0.000000,0.014560,0.000000
NaT,0.000000,0.000000,0.000000,0.0000,0.0000,0.0000,0.0000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [6]:
sorted(processed_df_map.keys())

['aud_df_processed',
 'cad_df_processed',
 'chf_df_processed',
 'eur_df_processed',
 'gbp_df_processed',
 'jpy_df_processed',
 'nok_df_processed',
 'nzd_df_processed',
 'sek_df_processed']