In [1]:
from pathlib import Path
import sys

cwd = Path.cwd()
if (cwd / "src").exists():
    project_root = cwd
elif (cwd.parent / "src").exists():
    project_root = cwd.parent
else:
    raise FileNotFoundError("Could not locate project root containing 'src'.")

if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

In [2]:
from src.data.build_ultimate_df import build_ultimate_df

ultimate_df = build_ultimate_df()
ultimate_df["aud"].tail()

c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'FX', column 'USDNOK Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'FX', column 'USDKRW Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'FX', column 'USDSGD Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'FX', column 'USDTWD Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'FX', column 'USDMXN Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'FX', column 'USDCNH Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'FX', column 'USDINR Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'FX', column 'BBDXY Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'FX', column 'EMFXDBET Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'USGG2YR Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'USGG5YR Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'USGG10YR Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'S0042FS 3M1M BLC Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'S0042FS 6M1M BLC Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'S0042FS 1Y1M BLC Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'RR2YHUS Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'SPX Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'FTW5000 Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'INDU Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'MXUS Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'BCOM Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'CO1 Comdty'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'XAU Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'FN1 Comdty'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'TZT1 Comdty'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'NG1 COMB Comdty'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'HGA Comdty'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'LMCADS03 Comdty'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'VIX Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'MOVE Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'JPMVG71M Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'EUR', column 'GECU2YR Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'EUR', column 'GECU5YR Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'EUR', column 'GECU10YR Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'EUR', column 'RR2YHEA Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'EUR', column 'GTITL10YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'EUR', column 'GTDEM10YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'EUR', column 'SXXP Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'JPY', column 'GTJPY2YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'JPY', column 'GTJPY5YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'JPY', column 'GTJPY10YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'JPY', column 'G0018 3M1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'JPY', column 'G0018 6M1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'JPY', column 'G0018 1Y1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'JPY', column 'JYSST10 BLC Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'JPY', column 'NXY Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CHF', column 'GTCHF2YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CHF', column 'GTCHF5YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CHF', column 'GTCHF10YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CHF', column 'G0082 3M1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CHF', column 'G0082 6M1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CHF', column 'G0082 1Y1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CHF', column 'SMI Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'GBP', column 'GTGBP2YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'GBP', column 'GTGBP5YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'GBP', column 'GTGBP10YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'GBP', column 'RR2YHGB Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'GBP', column 'UKX Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'GBP', column 'MCX Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NZD', column 'GTNZD2YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NZD', column 'GTNZD5YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NZD', column 'G0049 3M1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NZD', column 'G0049 6M1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NZD', column 'G0049 1Y1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NZD', column 'RR2YHnz Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NZD', column 'NZX20X Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NZD', column 'OMRA Comdty'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NZD', column 'FSPA Comdty'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'AUD', column 'GTAUD2YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'AUD', column 'GTAUD5YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'AUD', column 'G0001 3M1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'AUD', column 'G0001 6M1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'AUD', column 'G0001 1Y1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'AUD', column 'RR2YHAU Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'AUD', column 'AS51 Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'AUD', column 'SCOH6 COMB Comdty'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'AUD', column 'IACA COMB Comdty'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CAD', column 'GTCAD2YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CAD', column 'G0007 3M1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CAD', column 'G0007 6M1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CAD', column 'G0007 1Y1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CAD', column 'RR2YHCA Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CAD', column 'SPTSX Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CAD', column 'USCRWCAS Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NOK', column 'GTNOK2YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NOK', column 'GTNOK5YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NOK', column 'GTNOK10YR Corp'; those rows will be NaT
  warnings.warn(

,AUDUSD,BBDXY,Asia EMFX,2y yield,5y yield,10y yield,Real 2y yield,Local - S&P500,Local - Wilshire,Local - Dow Jones,...,Copper COMEX,Copper LME,MOVE Index,JPMVG71M Index,NG1 COMB Comdty,TZT1 Comdty,FN1 Comdty,VIX Index,SCOH6 COMB Comdty,IACA COMB Comdty
2026-02-13,-0.240062,-0.028539,0.209001,0.0083,0.0087,-0.0092,0.0483,-1.452188,-1.573509,-1.501229,...,0.290400,0.042708,70.10,7.73,3.243,32.500,76.25,20.60,96.75,222.0
2026-02-16,-0.014139,0.120210,-0.182634,-0.0190,-0.0260,-0.0390,0.0000,0.218239,0.218239,0.218239,...,0.000000,-0.237064,NaN,7.31,NaN,30.903,72.55,21.20,96.65,222.0
2026-02-17,0.197768,0.004691,0.052907,-0.0609,-0.0482,-0.0335,-0.0249,0.140366,0.151491,0.178291,...,-2.740845,-1.813948,68.84,7.30,3.031,29.822,71.13,20.29,96.19,221.0
2026-02-18,-0.240198,0.234805,0.033319,0.0018,0.0076,0.0189,-0.0312,-0.207262,-0.291892,-0.083269,...,2.493204,0.000000,NaN,7.30,2.974,31.410,76.41,18.98,95.72,221.0
NaT,0.000000,0.000000,0.000000,0.0000,0.0000,0.0000,0.0000,0.000000,0.000000,0.000000,...,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
ultimate_df["eur"].tail()

,EURUSD,BBDXY,EMFX,2y yield,5y yield,10y yield,3m1m forward OIS,6m1m forward OIS,1y1m forward OIS,Real 2y yield,...,Gold,Oil,Copper COMEX,Copper LME,MOVE Index,JPMVG71M Index,NG1 COMB Comdty,TZT1 Comdty,FN1 Comdty,VIX Index
2026-02-13,-0.025275,-0.034306,-0.02812,0.0243,0.0277,0.0258,0.01593,0.01824,0.02900,0.0483,...,2.405721,0.340061,0.290400,0.042708,70.10,7.73,3.243,32.500,76.25,20.60
2026-02-16,-0.143345,0.103941,0.00000,0.0050,0.0020,-0.0010,-0.00022,0.00385,0.01050,0.0000,...,-0.995811,1.319667,0.000000,-0.237064,NaN,7.31,NaN,30.903,72.55,21.20
2026-02-17,0.033747,0.008151,0.00000,-0.0299,-0.0282,-0.0255,0.00538,-0.03499,-0.03520,-0.0249,...,-2.313991,-1.807942,-2.740845,-1.813948,68.84,7.30,3.031,29.822,71.13,20.29
2026-02-18,-0.270293,0.220313,0.00000,-0.0142,-0.0194,-0.0141,-0.00572,-0.00504,-0.01237,-0.0312,...,2.433109,2.995329,2.493204,0.000000,NaN,7.30,2.974,31.410,76.41,18.98
NaT,0.000000,0.000000,0.00000,0.0000,0.0000,0.0000,0.00000,0.00000,0.00000,0.0000,...,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN